version: 2 # use CircleCI 2.0
jobs: # a collection of steps

  clamav:
    working_directory:  ~/docs
    docker: # run the steps with Docker
      - image: circleci/node
    steps:
      - run:
          name: cramAV test
          command: |
            # sudo apt-get -y update
            # sudo apt-get -y install clamav
            # sudo freshclam
            pwd
            # sudo clamscan --infected --remove --recursive ~/docs
  test:
    working_directory: ~/docs
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: update npm
          command: |
            sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: sudo npm modules install
          command: |
            sudo npm install
      - run:
          name: Testing Application
          command: |
            sudo npm run test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      # - linkcheck
      - clamav